version: '3.7'


# container to run tests and other developer activities
services:
  php:
    container_name: optional
    image: optional
    build:
      context: php
    volumes:
      - ./../:/var/app:cached
